### ISSUE TITLE
Docker image steps/ requirements

### ISSUE THREAD

**Issue by khanzzirfan** [WarleyGabriel/demo-webdriverio-mocha#1]
Hi Gabriel,
Thank you for setting up the repo. It is really helpful. 

But we cannot use the docker image that you have in the docker-compose.yml file. Could you give me more information about what is required in building the docker image. What all libraries are involved?

you help is really appreciated.
Thanks

**Comment by WarleyGabriel** [comment]
Hi @sahilkhan99,

Thank you.

It's only necessary:
- docker >= 18.x
- docker-compose >= 1.24.x

The docker-compose.yml will start Selenium container with https://opensource.zalando.com/zalenium/

If you have any questions or problems, you can send to me.
